version: '3.8'

services:
  users:
    build: ./users
    ports:
      - "8001:80"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/users"
      MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
    depends_on:
      - db
      - rabbitmq

  notifications:
    build: ./notifications
    ports:
      - "8002:80"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/notifications"
      MESSENGER_TRANSPORT_DSN: "amqp://guest:guest@rabbitmq:5672/%2f/messages"
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

